[package]
name = "libsolv-sys"
version = "0.1.0"
description = "Raw bindings to libsolv"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1"
pkg-config = "0.3"
bindgen = "0.57"
anyhow = "1"
cmake = "0.1"
